"""Build orchestration: a layer runs only after its intake gate (and its upstream gates) pass.

    bronze  ← project A, bronze A
    silver  ← project A, bronze A, silver B   (B = after profiling; includes A)
    gold    ← … + gold A, and silver current
    publish ← … + serve A, and gold current (consumers: no pending ★ + valid approval)
"""
from __future__ import annotations

import json

from . import config as C
from .intake import check
from .project import Project, audit
from .runtime import Lease, Results, VerificationError, ledger

GATES = {
    "bronze": [("project", "A"), ("bronze", "A")],
    "silver": [("project", "A"), ("bronze", "A"), ("silver", "B")],
    "gold": [("project", "A"), ("bronze", "A"), ("silver", "B"), ("gold", "A")],
    "publish": [("project", "A"), ("bronze", "A"), ("silver", "B"), ("gold", "A"), ("serve", "A")],
}
ALL = [("project", "A"), ("bronze", "A"), ("silver", "B"), ("gold", "A"), ("serve", "A")]
EXIT_BLOCKED, EXIT_FAILED = 2, 1


def gate(project: Project, layer: str, unattended: bool = False) -> tuple[bool, str, list]:
    reports = [check(project, skill, g, unattended=unattended) for skill, g in GATES[layer]]
    ok = all(r.ok for r in reports)
    text = "\n\n".join(r.render() for r in reports if not r.ok or r.warnings)
    return ok, text, reports


def pending_decisions(project: Project) -> list[dict]:
    """★ answers still pending (fast profile) — governance debt that blocks consumer release."""
    out = []
    from .intake import load_provenance
    for path, rec in load_provenance(project).items():
        if isinstance(rec, dict) and rec.get("state") == "pending":
            out.append({"path": path, "owner": rec.get("owner"), "due": rec.get("due", "")})
    return out


def write_debt(project: Project) -> None:
    items = pending_decisions(project)
    lines = ["# Governance debt", "", "*Generated by dwh_core. Human-owned (★) decisions still pending. "
             "The build may continue in the fast profile; releasing to consumers is blocked until each is "
             "answered by its owner.*", ""]
    lines += [f"- `{i['path']}` — waiting for **{i['owner']}**" + (f" (due {i['due']})" if i["due"] else "")
              for i in items] or ["- none"]
    C.atomic_write_text(project.loc("debt"), "\n".join(lines) + "\n")


def build(project: Project, layer: str, batch: str | None = None, source: str | None = None,
          unattended: bool = False, rebuild: bool = False) -> int:
    ok, text, _ = gate(project, layer, unattended)
    if not ok:
        print(f"BLOCKED — the {layer} build needs these inputs first (nothing was run):\n\n{text}")
        audit(project, f"build.{layer}.blocked")
        return EXIT_BLOCKED
    if text:
        print(text + "\n")
    write_debt(project)
    from . import generate
    res = Results(layer, source or "all")
    titles = {"bronze": "Bronze verification — ingress gates and record counts",
              "silver": "Silver verification — row law and post-conditions",
              "gold": "Gold verification — grain, golden values, reconciliation"}
    with Lease(project, f"dwh-{layer}"):
        try:
            if layer == "bronze":
                from . import bronze, profile
                bronze.build(project, res, only_source=source, only_batch=batch)
                profile.run(project)
            elif layer == "silver":
                from . import silver
                generate.render_layer(project, "silver")
                silver.build(project, res, force_rebuild=rebuild)
            elif layer == "gold":
                from . import gold, silver
                cur, why = silver.is_current(project)
                if not cur:
                    print(f"BLOCKED — {why}. Run the silver build first (`dwh build silver`).")
                    return EXIT_BLOCKED
                generate.render_layer(project, "gold")
                gold.build(project, res)
        except VerificationError as e:
            res.write(project, f"{layer}-verify", titles[layer], f"**FAILED** — nothing from the failing batch "
                      f"was committed.\n\n```\n{e}\n```")
            audit(project, f"build.{layer}.failed", reason=str(e)[:400])
            print(f"FAILED — {layer} verification:\n{e}\nSee {project.rel(project.layout.report(layer + '-verify'))}")
            return EXIT_FAILED
        except Exception as e:
            from . import silver
            if isinstance(e, (silver.NoBronzeData, silver.SpecError, generate.TamperedFile)):
                audit(project, f"build.{layer}.blocked", reason=str(e)[:400])
                print(f"BLOCKED — {e}")
                return EXIT_BLOCKED
            raise
    path = res.write(project, f"{layer}-verify", titles[layer], _intro(project, layer, res))
    audit(project, f"build.{layer}.done", passed=not res.failures)
    print(summary(project, layer, res))
    print(f"\nverification: {path.relative_to(project.root)}")
    return 0 if not res.failures else EXIT_FAILED


def _intro(project: Project, layer: str, res: Results) -> str:
    return "**PASS** — every fatal check held before COMMIT." if not res.failures else "**FAILED**"


def summary(project: Project, layer: str, res: Results) -> str:
    lines = [f"{layer}: {'PASS' if not res.failures else 'FAILED'} — {len(res.checks)} checks, "
             f"{len(res.failures)} failed"]
    if layer == "bronze":
        f = res.facts
        lines.append(f"  landed rows: {f.get('landed_rows', 0)} · batches skipped (same content): "
                     f"{f.get('skipped_batches', 0)} · files rejected: {f.get('rejected_files', 0)}")
        if f.get("rejected_files"):
            lines.append(f"  rejected files and reasons: {project.rel(project.loc('dead_letter') / 'rejected_files.csv')}")
        lines.append(f"  profile: {project.rel(project.loc('bronze_profile'))}")
    elif layer == "silver":
        for k, v in res.facts.items():
            if isinstance(v, dict) and "batch_rows" in v:
                lines.append(f"  {k}: {v['batch_rows']} rows → {v['survivors']} kept, {v['dead_lettered']} "
                             f"dead-lettered, {v['duplicates']} duplicates · table {v['rows_before']} → {v['rows_after']}")
        if not any(isinstance(v, dict) and "batch_rows" in v for v in res.facts.values()):
            lines.append("  nothing new to process (all bronze batches already in silver)")
    elif layer == "gold":
        for k, v in res.facts.items():
            if k.endswith("|rows"):
                lines.append(f"  {k.split('|')[0]}: {v} rows")
    return "\n".join(lines)


def check_all(project: Project, unattended: bool = False) -> tuple[bool, str]:
    reps = [check(project, s, g, unattended=unattended) for s, g in ALL]
    return all(r.ok for r in reps), "\n\n".join(r.render() for r in reps)


def status_text(project: Project) -> str:
    from . import approvals
    m = project.manifest
    lines = [f"# dwh status — {m.get('name', '?')} (profile {project.profile_mode})", ""]
    lines.append("## Intake gates")
    for s, g in ALL:
        try:
            r = check(project, s, g)
            extra = f", {len(r.warnings)} pending ★" if r.warnings else ""
            lines.append(f"- {s} (gate {g}): {'PASS' if r.ok else f'BLOCKED — {len(r.errors)} item(s)'}{extra}")
        except Exception as e:  # a broken spec must not hide the rest of the status
            lines.append(f"- {s} (gate {g}): cannot check — {str(e)[:120]}")
    bl = ledger(project, "bronze")
    lines += ["", "## Bronze"]
    per = {}
    for k, v in bl.items():
        if "|" in k and not k.startswith("types|") and isinstance(v, dict):
            s, b = k.split("|", 1)
            per.setdefault(s, []).append((b, v))
    for s, items in per.items():
        items.sort()
        b, v = items[-1]
        lines.append(f"- {s}: {len(items)} batch(es), latest {b} (v{v.get('version')}, {v.get('landed')} rows"
                     + (f", {v.get('parse_rejects')} unparseable" if v.get("parse_rejects") else "") + ")")
    if not per:
        lines.append("- nothing landed yet")
    sl = ledger(project, "silver")
    lines += ["", "## Silver"]
    for e, v in sl.items():
        n = sum(len(x) for x in (v.get("sources") or {}).values())
        lines.append(f"- {e}: {v.get('rows_after')} rows after {n} batch(es)")
    if not sl:
        lines.append("- not built yet")
    gl = ledger(project, "gold")
    lines += ["", "## Gold"]
    if gl:
        from . import gold
        cur, why = gold.is_current(project)
        lines.append(f"- tables: {json.dumps(gl.get('tables'))} · verified {gl.get('at')} · "
                     + ("current" if cur else f"STALE ({why})"))
    else:
        lines.append("- not built yet")
    pub = project.loc("serving") / "CURRENT"
    lines += ["", "## Published"]
    lines.append(f"- CURRENT → {pub.read_text().strip()}" if pub.exists() else "- nothing published yet")
    rel = project.loc("serving") / "RELEASED"
    if rel.exists():
        lines.append(f"- RELEASED to consumers → {rel.read_text().strip()}")
    try:
        a = approvals.status(project)
        lines.append(f"- approval: {'valid' if a['approved'] else ('STALE — specs changed after approval' if a['stale'] else 'none')}"
                     + (f" (by {a['approved_by']})" if a.get("approved_by") else ""))
    except Exception:
        pass
    pend = pending_decisions(project)
    if pend:
        lines += ["", "## Pending human decisions (block consumer release)"]
        lines += [f"- `{p['path']}` — {p['owner']}" for p in pend]
    try:
        from .workbook import star_kept_paths, star_kept_summary
        kept = star_kept_paths(project)
        if kept:
            lines += ["", f"## ★ decisions taken by keeping a proposed workbook default ({len(kept)})",
                      "Recorded as the owner's answers; listed so a reviewer can give them a second look."]
            lines += [f"- {t}" for t in star_kept_summary(project, kept)]
    except Exception:  # status must never fail on this
        pass
    return "\n".join(lines)
